### ISSUE TITLE
Zehlendorf IPv6 results in internal server error

### ISSUE THREAD

**Issue by andrenarchy** [freifunk-berlin/config.berlin.freifunk.net#46]

**Comment by booo** [comment]
We ran out of disk space. Can you check again?

**Comment by andrenarchy** [comment]
nope, still broken... just pick "Wahlkreis 79" in the expert form...

**Comment by booo** [comment]
Excerpt from the nipapd log file:
```
2016-12-20 12:41:20,053 ERROR: Exception on /expert/form [POST][in /usr/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/expert.py", line 40, in expert_form
    prefixes_v6)
  File "./app/utils.py", line 43, in request_create
    get_api().allocate_ips(pool, r.id, r.email, name, prefix_len, 6)
  File "./app/nipap.py", line 135, in allocate_ips
    family, data=data)
  File "./app/nipap.py", line 123, in create_prefix_from_pool
    prefix = self._create_prefix(pool, prefix_type, family, prefix_len, data=data)
  File "./app/nipap.py", line 107, in _create_prefix
    prefix.save(args)
  File "/usr/lib/python2.7/dist-packages/pynipap.py", line 1225, in save
    raise _fault_to_exception(xml_fault)
NipapInputError: No prefixes in pool
```

Seems like all prefixes in the pool for Wahlkreis 79 are gone. Maybe we should double check this in the nipap frontend?

I can give you access to the system if you want to tackle the problem.

Maybe we should bring this to the attention of the other maintainers on the mailinglist?

**Comment by andrenarchy** [comment]
I don't have time to investigate this so feel free to drop a line on the mailinglist!

We just picked another district in our workshop yesterday – worked as expected! :)

**Comment by rtznprmpftl** [comment]
i'm going to close this issue since its not applicable anymore

**Comment by SvenRoederer** [comment]
Still fails for me with an "500" error

**Comment by rtznprmpftl** [comment]
That pool didn't have any prefixes assigned, therefore the app failed.

This is now fixed in the data of nipap
