### ISSUE TITLE
exhausted ip pool results in internal server error on request of new ips

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/config.berlin.freifunk.net#51]
Requesting IPs from a pool that is exhausted results in an internal server error when using the expert form. We should handle this case properly and tell the user to e.g. request a smaller address range.

From the logs:
```
2020-01-09 14:09:59,477 ERROR: Exception on /expert/form [POST][in /usr/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/expert.py", line 40, in expert_form
    prefixes_v6)
  File "./app/utils.py", line 39, in request_create
    get_api().allocate_ips(pool, r.id, r.email, name, prefix_len, 4)
  File "./app/nipap.py", line 135, in allocate_ips
    family, data=data)
  File "./app/nipap.py", line 123, in create_prefix_from_pool
    prefix = self._create_prefix(pool, prefix_type, family, prefix_len, data=data)
  File "./app/nipap.py", line 107, in _create_prefix
    prefix.save(args)
  File "/usr/lib/python2.7/dist-packages/pynipap.py", line 1225, in save
    raise _fault_to_exception(xml_fault)
NipapNonExistentError: no free prefix found
```

**Comment by kls0e** [comment]
The wizard shows the same behavior with standard mode.

**Comment by nicolasberens** [comment]
this was fixed by extending the pool
