### ISSUE TITLE
request IPv6 for "Treptow/Köpenick" causes internal server error

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/config.berlin.freifunk.net#54]
When requesting an IPv6-Address for "Treptow/Köpenick" the server results in an internal server error.
This was seen in "expert Mode", even when requesting an IPv6-address only.

**Comment by SvenRoederer** [comment]
This seems like https://github.com/freifunk-berlin/config.berlin.freifunk.net/issues/46 and probably relates to #51 also.

**Comment by rtznprmpftl** [comment]
Did the email address use an umlaut by any chance? (or any other non ASCII Character?)

**Comment by rtznprmpftl** [comment]
This issue is caused by the umlaut in Köpenick

**Comment by rtznprmpftl** [comment]
We temporarily fixed it by removing the Umlauts,
For future reference, the app fails since it gets an UTF8 string here where it expects ascii https://github.com/freifunk-berlin/config.berlin.freifunk.net/blob/master/app/nipap.py#L53

```
[2022-03-19 17:56:22,648] ERROR in app: Exception on /expert/form [POST]
Traceback (most recent call last):
  File "/var/www/nipap-wizard/env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/nipap-wizard/env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/nipap-wizard/env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/nipap-wizard/env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/nipap-wizard/env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app/expert.py", line 40, in expert_form
    prefixes_v6)
  File "./app/utils.py", line 43, in request_create
    get_api().allocate_ips(pool, r.id, r.email, name, prefix_len, 6)
  File "./app/nipap.py", line 135, in allocate_ips
    family, data=data)
  File "./app/nipap.py", line 119, in create_prefix_from_pool
    pool = self.get_pool_by_name(pool_name)
  File "./app/nipap.py", line 67, in get_pool_by_name
    return self._get_one_by(pynipap.Pool, 'name', name)
  File "./app/nipap.py", line 58, in _get_one_by
    req = self._get_by(cls, val1, val2)
  File "./app/nipap.py", line 53, in _get_by
    'val2': str(val2)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 29: ordinal not in range(128)

```

**Comment by Akira25** [comment]
This error does not occur anymore in the recent version of the service. This was achieved by converting Umlaute to ligatures.
